### PR TITLE
feat: support timeout-minutes 

### LINKED ISSUE #53: Configure timeout-minutes
The action should specify the maximum amount of minutes the tests can run, otherwise they could get stuck for hours:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

### PR DESCRIPTION
**Pull request by dominykas**
Closes #53

Tested in https://github.com/dominykas/pkgjs-action/pull/7:

- sleep and fail: https://github.com/dominykas/pkgjs-action/actions/runs/4197256901/jobs/7279342016
- go fast and do not fail: https://github.com/dominykas/pkgjs-action/actions/runs/4197273460/jobs/7279382615

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
360 is a pretty massive default; only one of my projects has it set to more then 30.

**Comment by dominykas** [comment]
> 360 is a pretty massive default

Indeed, but that's the same as the one in Github... Not that we haven't overridden some of their other defaults here.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ljharb** [comment]
¯\\\_(ツ)_/¯ we can keep it this way for sure, but for JS public projects do we really expect they need *six hours* to complete?

**Comment by mcollina** [comment]
Oh I'd be fine with 15 minutes. GitHub would probably thank us!

**Comment by dominykas** [comment]
Decreased the default to 30m. I figure that's roughly the limit where CI starts to need optimizations anyways.

**Pull request merged**
